-- CREATE TABLE users (
--     id SERIAL PRIMARY KEY NOT NULL,
--     user_identifier VARCHAR(100) NOT NULL UNIQUE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
-- );

CREATE TABLE discussions (
    id SERIAL PRIMARY KEY NOT NULL,
    -- user_id INTEGER REFERENCES users(id) NOT NULL,
    caractere TEXT,
    discussion TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
